const KEY='rhythm_os_v32_entries',LEGACY31='rhythm_os_v31_entries',LEGACY3='rhythm_os_v3_entries',LEGACY2='rhythm_os_v2_entries',THEME='rhythm_os_theme';const dayparts=['Morning','Afternoon','Evening','Night'];const icons={Morning:'☀',Afternoon:'◐',Evening:'◒',Night:'☾'};const quick=['Breakfast','Coffee','Walk','Workout','Meeting','Admin','Voice Router','Build','Lunch','Errand','Dinner','Family','Read','Sleep'];let entries=load(),activeDate=todayKey();
function todayKey(d=new Date()){return`${d.getFullYear()}-${String(d.getMonth()+1).padStart(2,'0')}-${String(d.getDate()).padStart(2,'0')}`}
function label(){return new Date(`${activeDate}T12:00:00`).toLocaleDateString([],{weekday:'short',month:'short',day:'numeric'})}
function time(iso){return new Date(iso).toLocaleTimeString([],{hour:'2-digit',minute:'2-digit',hour12:false})}
function hm(d=new Date()){return`${String(d.getHours()).padStart(2,'0')}:${String(d.getMinutes()).padStart(2,'0')}`}
function isoFromHM(s){let [h,m]=s.split(':').map(Number),d=new Date();d.setHours(h,m,0,0);return d.toISOString()}
function mins(iso){let d=new Date(iso);return d.getHours()*60+d.getMinutes()}
function interval(a,b){let delta=mins(b)-mins(a);if(delta<0)delta+=1440;return`${delta} min`}
function uid(){return crypto&&crypto.randomUUID?crypto.randomUUID():`id-${Date.now()}`}
function esc(s=''){return String(s||'').replace(/[&<>'"]/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;',"'":'&#39;','"':'&quot;'}[c]))}
function load(){try{for(const k of [KEY,LEGACY31,LEGACY3,LEGACY2]){let v=JSON.parse(localStorage.getItem(k))||[];if(v.length){if(k!==KEY)localStorage.setItem(KEY,JSON.stringify(v));return v}}return[]}catch{return[]}}
function save(){localStorage.setItem(KEY,JSON.stringify(entries))}
function set(id,v){let e=document.getElementById(id);if(e)e.textContent=v}
function current(){let h=new Date().getHours();return h<12?'Morning':h<17?'Afternoon':h<21?'Evening':'Night'}
function todays(){return entries.filter(e=>e.date===activeDate).sort((a,b)=>dayparts.indexOf(a.daypart)-dayparts.indexOf(b.daypart)||(a.order||0)-(b.order||0)||new Date(a.occurredAt||a.createdAt)-new Date(b.occurredAt||b.createdAt))}
function by(dp){return todays().filter(e=>e.daypart===dp).sort((a,b)=>(a.order||0)-(b.order||0)||new Date(a.occurredAt||a.createdAt)-new Date(b.occurredAt||b.createdAt))}
function syncOccurredLabel(){let t=entryForm.occurredTime.value||hm(); occurredBtn.textContent=`${t} ▾`; hiddenTimePicker.value=t}
function init(){if(localStorage.getItem(THEME)==='dark')document.documentElement.classList.add('dark');document.querySelectorAll('.nav-btn').forEach(b=>b.onclick=()=>view(b.dataset.view));themeBtn.onclick=()=>{document.documentElement.classList.toggle('dark');localStorage.setItem(THEME,document.documentElement.classList.contains('dark')?'dark':'light')};fab.onclick=()=>view('add');entryForm.onsubmit=saveEntry;occurredBtn.onclick=()=>{hiddenTimePicker.value=entryForm.occurredTime.value||hm(); if(hiddenTimePicker.showPicker){hiddenTimePicker.showPicker()} else {hiddenTimePicker.focus(); hiddenTimePicker.click()}};hiddenTimePicker.onchange=()=>{entryForm.occurredTime.value=hiddenTimePicker.value||hm();syncOccurredLabel()};exportBtn.onclick=exportData;importFile.onchange=importData;clearBtn.onclick=()=>{if(confirm('Clear all Rhythm OS data?')){entries=[];save();render()}};entryForm.daypart.value=current();entryForm.occurredTime.value=hm();syncOccurredLabel();quickChips.innerHTML=quick.map(q=>`<button type="button">${q}</button>`).join('');quickChips.querySelectorAll('button').forEach(b=>b.onclick=()=>{entryForm.entry.value=b.textContent;entryForm.entry.focus()});render()}
function view(id){document.querySelectorAll('.view').forEach(v=>v.classList.remove('active'));document.getElementById(id).classList.add('active');document.querySelectorAll('.nav-btn').forEach(b=>b.classList.toggle('active',b.dataset.view===id));fab.style.display=id==='add'?'none':'grid'; if(id==='add'&&!entryForm.editId.value){entryForm.occurredTime.value=hm();syncOccurredLabel()} scrollTo({top:0,behavior:'smooth'})}
function saveEntry(ev){ev.preventDefault();let f=ev.target,now=new Date(),id=f.editId.value,ex=entries.find(e=>e.id===id),dp=f.daypart.value;if(ex){ex.daypart=dp;ex.entry=f.entry.value.trim();ex.note=f.note.value.trim();ex.occurredAt=isoFromHM(f.occurredTime.value||hm());ex.updatedAt=now.toISOString()}else{entries.push({id:uid(),date:activeDate,daypart:dp,entry:f.entry.value.trim(),note:f.note.value.trim(),occurredAt:isoFromHM(f.occurredTime.value||hm()),recordedAt:now.toISOString(),createdAt:now.toISOString(),updatedAt:now.toISOString(),order:by(dp).length})}renormalize();save();f.reset();f.editId.value='';f.daypart.value=current();f.occurredTime.value=hm();syncOccurredLabel();render();view('home')}
function renormalize(){dayparts.forEach(dp=>by(dp).forEach((e,i)=>e.order=i))}
function render(){let items=todays();set('todayLabel',label());set('entryCount',items.length);set('headline',`${items.length} entr${items.length===1?'y':'ies'}`);set('flowLabel',items.length>=6?'Rhythm visible':'Building rhythm');currentDaypart.textContent=`Current container: ${current()}`;daypartCards.innerHTML=dayparts.map(daypartCard).join('');timeline.innerHTML=items.length?dayparts.map(timelineSection).join(''):'<div class="empty-card muted">No entries yet. Tap + to add the first move.</div>';dayparts.forEach(dp=>{let key=dp.toLowerCase(),list=document.getElementById(`${key}List`);if(list)list.innerHTML=by(dp).length?by(dp).map((e,i)=>entryHtml(e,i,dp)).join(''):`<div class="empty-card muted">No ${key} entries yet.</div>`})}
function daypartCard(dp){let list=by(dp),last=list.at(-1);return`<article class="daypart-tile" onclick="view('${dp.toLowerCase()}')"><div class="tile-icon">${icons[dp]}</div><div><strong>${dp}</strong><p class="muted small">${list.length} entr${list.length===1?'y':'ies'}</p>${last?`<p class="last">Last: ${esc(last.entry)}</p>`:''}</div></article>`}
function timelineSection(dp){let list=by(dp);if(!list.length)return'';return`<section class="timeline-section"><h4>${icons[dp]} ${dp}</h4>${list.map((e,i)=>mini(e,i,list)).join('')}</section>`}
function mini(e,i,list){let gap=i>0?`<div class="gap-line"><span>${interval(list[i-1].occurredAt||list[i-1].createdAt,e.occurredAt||e.createdAt)}</span></div>`:'';return`${gap}<article class="mini-card"><div class="mini-main">${esc(e.entry)}</div><div class="mini-time">${time(e.occurredAt||e.createdAt)}</div></article>`}
function entryHtml(e,i,dp){let list=by(dp),gap=i>0?`<div class="gap-line"><span>${interval(list[i-1].occurredAt||list[i-1].createdAt,e.occurredAt||e.createdAt)}</span></div>`:'';return`<article class="entry">${gap}<div class="entry-main">${esc(e.entry)}</div><div class="entry-meta"><span>${time(e.occurredAt||e.createdAt)}</span><span>Recorded ${time(e.recordedAt||e.createdAt)}</span></div>${e.note?`<p class="muted small">${esc(e.note)}</p>`:''}<div class="entry-actions"><button onclick="moveEntry('${e.id}',-1)">↑</button><button onclick="moveEntry('${e.id}',1)">↓</button><button onclick="editEntry('${e.id}')">Edit</button><button class="delete" onclick="deleteEntry('${e.id}')">Delete</button></div></article>`}
function editEntry(id){let e=entries.find(x=>x.id===id);if(!e)return;view('add');entryForm.editId.value=e.id;entryForm.daypart.value=e.daypart;entryForm.entry.value=e.entry;entryForm.note.value=e.note||'';entryForm.occurredTime.value=hm(new Date(e.occurredAt||e.createdAt));syncOccurredLabel()}
function deleteEntry(id){if(confirm('Delete this entry?')){entries=entries.filter(e=>e.id!==id);renormalize();save();render()}}
function moveEntry(id,dir){let e=entries.find(x=>x.id===id);if(!e)return;let list=by(e.daypart),idx=list.findIndex(x=>x.id===id),sw=list[idx+dir];if(!sw)return;let t=e.order||0;e.order=sw.order||0;sw.order=t;save();render()}
function exportData(){let blob=new Blob([JSON.stringify({app:'Rhythm OS',version:'3.2',exportedAt:new Date().toISOString(),entries},null,2)],{type:'application/json'}),a=document.createElement('a');a.href=URL.createObjectURL(blob);a.download=`rhythm-os-v32-export-${todayKey()}.json`;a.click();URL.revokeObjectURL(a.href)}
function importData(ev){let f=ev.target.files[0];if(!f)return;let r=new FileReader();r.onload=()=>{try{let d=JSON.parse(r.result);if(Array.isArray(d.entries)){entries=[...d.entries,...entries];renormalize();save();render();alert('Import complete.')}else alert('Import file did not contain entries.')}catch{alert('Could not import JSON.')}};r.readAsText(f);ev.target.value=''}
window.view=view;window.editEntry=editEntry;window.deleteEntry=deleteEntry;window.moveEntry=moveEntry;init();